version: "3"
services:
  patientdb:
    image: 'mysql:8.0.27'
    container_name: patientdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mediscreenapp
    ports:
      - "3306:3306"
    volumes:
      - /Users/lime/mediscreen-patient:/var/lib/mysql

  mediscreen-patient:
    image: mediscreen-patient
    container_name: mediscreen-patient
    restart: always
    build:
      context: "./"
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: patientdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - patientdb

